###############################
##### Output and run type #####

# If prevFile is not commented, the fitter will search for prevFile and continue the MCMC chain
# from where it left off. ====> This field is compulsory when calculating derived quantities! <====
#prevFile: "outputs/test_fit_CC_10MeV_-2BG_deltam4.5"
outFile:  "outputs/test_fit"

# Will you run in "LLH" (Log likelihood scan), "MCMC" (Markov Chain Monte-Carlo fit), or "derived" (calculate derived quantities from an existing fit) mode?
RunMode: "MCMC"  

Asimov: true    # Data fit or Asimov fit?
fastFit: true   # Accelerate calculations by simplifying the earth model and averaging the solar density over the production region (recommended)

singleChannel: CC  # Choose to run a single channel in the fit: false (both), CC, ES. False unless otherwise specified

##############################
##### Asimov true values #####

# the total HEP flux can be thought as HEP discovery

true_sin2_th12: 0.307
true_sin2_th13: 0.0224
true_dm2_21: 7.5e-5 # PDG: 7.53e-5,  SNO: 5.113e-5
true_integrated_HEP_flux: 8250.0 # as given by b16_agss09


###############################
##### Prior distributions #####

##### Priors on mixing parameters

prior_sin2_th12: Uniform(0.23, 0.5) 
prior_sin2_th13: Truncated(Normal(0.022, 0.0007), 0.005, 0.035) # REACTOR CONSTRAINT: Truncated(Normal(0.022, 0.0007), 0.005, 0.035)
prior_dm2_21: Uniform(2e-5, 3e-4)

##### Priors on systematic parameters

# THERE ARE SEVERAL REASONABLE SETUPS HERE:
# leave the flux free:
# prior_8B_flux: Uniform(1e5, 2e7) # Free flux

# have the flux uncertainty equal to the Borexino constraint (~12%)
# prior_8B_flux: Truncated(Normal(5.46e6, 0.66e6), 0.1, 1e7) # 'True' uncertainty

# have the flux uncertainty smaller than current constraints to simulate the constraint -->
# --> we would get via an ES (flavour sensitive) measurement
prior_8B_flux: Truncated(Normal(5.46e6, 0.218e6), 1.5e6, 1e7) #4% uncertainty

# the total HEP flux can be thought as HEP discovery

prior_HEP_flux: Uniform(0, 2e4) # Assume at most 2-3 orders of magnitude smaller than 8B flux


###########################
##### MCMC parameters #####

nChains: 10
nSteps: 10000 # Number of post-stabilisation steps

maxTuningAttempts: 30 # Set  to zero for no adaptive stepsize tuning
nTuning: 2500 # Number of tuning steps on each cycle

# Turn on and off different uncertainties (turning off parameters makes the fit faster)
earth_potential_uncertainties: true 


##########################
##### LLH parameters #####

llh_bins: 15


#################################
##### MC and fit properties #####40

CC_exposure: 10 # in module years (10s of kTon years)
ES_exposure: 10 # in module years (10s of kTon years)

##### Background rates in Hz / module

# Nominal values:
# ? ES backgrounds
# neutrons: 4.98 Hz/module 
# gammas: 1.145 x neutrons = 5.70 Hz/module

ES_background_normalisations: [2] 
CC_background_normalisations: [4.98, 5.70]

ES_background_systematics: [0.] # Fractional rate uncertainty
CC_background_systematics: [0., 0.] # Fractional rate uncertainty

nBins_Etrue: 30

range_Etrue: [0.1, 20]

nBins_Ereco_ES: 40

nBins_Ereco_CC: 40

range_Ereco_ES: [2, 20]
range_Ereco_CC: [5, 25]

Ereco_min_ES: 5
Ereco_min_CC: 10

nBins_cosz: 40


#######################
##### Input files #####

# Prior covariance matrix and default values for nuisance parameters
# Must be a jld2 file with a 'covariance' matrix object and a 'true' vector object
earth_normalisation_prior_file: "inputs/earth_uncertainty_cov.jld2"

# Optional: covariance matrix for proposal function (covariance matrix from a posterior) to help with stepsizes
# Must be a jld2 file with a 'posterior_cov' matrix object

### Comment out if not desired ###
# proposal_matrix: "outputs/posterior_covariance.jld2"

# Matter potential and oscillation files
solar_model_file: "inputs/AGSS09_high_z.jld2"
flux_model_file: "inputs/fluxes.jld2"
earth_model_file: "inputs/EARTH_MODEL_PREM_DENSE.dat"
earth_uncertainty_file: "inputs/earth_uncertainty_4.5e-5.jld2"
solar_exposure_file: "inputs/solarExposure.csv"

# Detector response files ###### NOT UPDATED. AT THE MOMENT YOU ARE EXPECTED TO USE YOUR OWN!!!!
reconstruction_sample_CC: "inputs/sergio_reco_CC_withMediumCuts.csv"
reconstruction_sample_ES_nue: "inputs/ES_reconstruction_250kevts_flatdistrib_noCrossSection_GeV_june2025.csv"
reconstruction_sample_ES_nuother: "inputs/ES_reconstruction_250kevts_flatdistrib_noCrossSection_GeV_june2025.csv"

# Background files ###### NOT UPDATED. AT THE MOMENT YOU ARE EXPECTED TO USE YOUR OWN!!!!
CC_background_files: ["inputs/neutron_bg_CC_sergio_withCuts.csv", "inputs/gamma_bg_CC_sergio_withCuts.csv"]
ES_background_files: ["inputs/Ereco_NGamma_1e6-1_evts_GeV_june2025_v2.csv"]

data_file: "data.txt"
