################################################################################
#                    Solar Oscillation Fitter Configuration                    #
################################################################################
#
# This configuration file controls all aspects of the solar neutrino oscillation
# analysis. It serves as both a working configuration and a tutorial for new users.
#
# QUICK START GUIDE:
# 1. Set RunMode to "MCMC" for parameter estimation
# 2. Choose Asimov: true for simulation studies, false for real data
# 3. Set singleChannel to false (both), "ES", or "CC" 
# 4. Adjust nSteps and nChains for desired precision vs runtime
# 5. Modify prior distributions based on external constraints
# 6. Update file paths to point to your input data
#
# ANALYSIS MODES:
# - MCMC: Bayesian parameter estimation 
# - LLH: Likelihood scanning for quick tests
# - derived: Post-process existing chains for observables
#
#
################################################################################

###############################
##### Output and run type #####

# Output file prefix for all generated files (chains, plots, etc.)
# Results will be saved as: outFile_mcmc.bin, outFile_info.txt, etc.
outFile: "outputs/CC_5MeVthershold_noShielding_strongCuts_deltam6"

# Previous file to continue MCMC chain from (optional)
# Uncomment to resume a previous run from where it left off
# REQUIRED when RunMode is "derived" to specify which chain to post-process
#prevFile: "outputs/test_fit_CC_10MeV_-2BG_deltam4.5"

# Analysis mode selection:
# "MCMC"   - Bayesian parameter estimation with Markov Chain Monte Carlo
# "LLH"    - Likelihood scanning over 2D parameter slices
# "derived" - Post-process existing MCMC chain to calculate derived quantities
RunMode: "MCMC"

# Data type selection:
# true  - Asimov dataset (use theoretical predictions as "data")
# false - Real data analysis (requires data_file)
Asimov: true

# Computational speed optimization:
# true  - Fast mode: simplified Earth model, averaged solar densities (recommended)
# false - Slow mode: full Earth model, detailed solar density integration (slightly more accurate)
fastFit: true

# Detection channel selection:
# false - Fit both ES (Elastic Scattering) and CC (Charged Current) channels
# "ES"  - Fit only Elastic Scattering channel
# "CC"  - Fit only Charged Current channel
singleChannel: CC

##############################
##### Asimov true values #####

# True parameter values used to generate Asimov (fake) data
# These represent the "ground truth" that the analysis should recover
# Only used when Asimov: true

# Solar neutrino mixing parameters (dimensionless)
true_sin2_th12: 0.307    # Solar mixing angle
true_sin2_th13: 0.0224   # Reactor mixing angle
# The complex phase is irrelevant in this analysis and is fixed to zero
# The atmospheric mixing angle is also irrelevant and is fixed to 0.5

# Mass-squared differences (eV²)
true_dm2_21: 6e-5        # Solar mass-squared difference
                         # PDG 2020: 7.53e-5, SNO: 5.113e-5

# Solar neutrino flux normalizations (neutrinos/cm²/s)
true_integrated_HEP_flux: 8250.0  # HEP neutrino flux (B16-AGSS09 prediction)
                                  # Used for HEP neutrino discovery studies


###############################
##### Prior distributions #####

# Prior probability distributions for all fitted parameters
# Format: DistributionType(parameters)
# Available: Objects from the Distributions.jl package

##### Neutrino oscillation parameters #####

# Solar mixing angle squared sin²θ₁₂
prior_sin2_th12: Uniform(0.23, 0.5)
#Uniform prior covering region of interest: Uniform(0.15, 0.5)

# Reactor mixing angle squared sin²θ₁₃  
prior_sin2_th13: Truncated(Normal(0.022, 0.0007), 0.005, 0.035)
# Gaussian prior from reactor neutrino experiments: Truncated(Normal(0.022, 0.0007), 0.005, 0.035)
# Alternative conservative constraint: Uniform(0.0, 0.1)

# Solar mass-squared difference Δm²₂₁ (eV²)
prior_dm2_21: Uniform(2e-5, 3e-4)
# Conservative range covering experimental uncertainties

##### Solar flux systematic parameters #####

# ⁸B solar neutrino flux (neutrinos/cm²/s)
# Choose one of the following scenarios:

# Option 1: Free flux (no external constraint)
# prior_8B_flux: Uniform(1e5, 2e7)

# Option 2: Current Borexino constraint (~12% uncertainty)
# prior_8B_flux: Truncated(Normal(5.46e6, 0.66e6), 0.1, 1e7)

# Option 3: Future ES measurement constraint (4% uncertainty)
prior_8B_flux: Truncated(Normal(5.46e6, 0.218e6), 1.5e6, 1e7)

# HEP neutrino flux (neutrinos/cm²/s)
prior_HEP_flux: Uniform(0, 2e4)
# Conservative upper bound ~2-3 orders of magnitude below ⁸B flux
# Used for HEP neutrino discovery sensitivity studies


###########################
##### MCMC parameters #####

# Markov Chain Monte Carlo sampling configuration
# More chains and steps = better statistics but longer runtime

nChains: 10             # Number of parallel MCMC chains (recommended: number of available cores)
nSteps: 15000           # Number of post-tuning steps per chain
                        # Total samples = nChains × nSteps

# Adaptive step size tuning (improves sampling efficiency)
maxTuningAttempts: 30   # Maximum tuning cycles (0 = no tuning, faster but less efficient)
nTuning: 1000          # Steps per tuning cycle (recommended: O(1000))

# Systematic uncertainty toggles (disabling speeds up computation)
earth_potential_uncertainties: true  # Include Earth matter density uncertainties
                                     # Requires earth_normalisation_prior_file


##########################
##### LLH parameters #####

# Likelihood scanning configuration (only used when RunMode: "LLH")
llh_bins: 15            # Number of bins per parameter dimension for 2D scans
                        # Higher values = finer resolution but longer runtime


#################################
##### Detector configuration #####

# Detector exposure (determines event statistics)
CC_exposure: 40         # Charged Current exposure in module-years
ES_exposure: 40         # Elastic Scattering exposure in module-years
                        # 1 module-year ≈ 10 kton-year for DUNE

##### Background event rates #####

# Background normalizations (events/second/module before cuts ---still after efficiency atm---)
ES_background_normalisations: [4e-6]       # ES background components
CC_background_normalisations: [1.01, 1.01] # CC background components [neutrons, gammas]

# Background systematic uncertainties (fractional)
ES_background_systematics: [0.02]         # 2% uncertainty on ES backgrounds  
CC_background_systematics: [0.02, 0.02]   # 2% uncertainty on each CC background

# Note: Background files must match the number of components specified above
# ES: 1 component, CC: 2 components (neutrons + gammas)

##### Energy binning configuration #####

# True neutrino energy binning (for oscillation calculations)
nBins_Etrue: 40         # Number of true energy bins
range_Etrue: [0.1, 25]  # True energy range in MeV

# Reconstructed energy binning (for detector response)
nBins_Ereco_ES: 40      # ES reconstructed energy bins
nBins_Ereco_CC: 40      # CC reconstructed energy bins

range_Ereco_ES: [0.1, 25]  # ES energy range in MeV
range_Ereco_CC: [5, 25]    # CC energy range in MeV

# Analysis energy thresholds (events below these energies are excluded)
Ereco_min_ES: 0.1       # ES threshold in MeV
Ereco_min_CC: 5         # CC threshold in MeV

# Zenith angle binning (for Earth matter effects)
nBins_cosz: 40          # Number of cos(zenith) bins from -1 (upward) to 0 (horizontal)


#######################
##### Input files #####

##### Earth matter and solar model files #####

# Earth matter density uncertainties (required if earth_potential_uncertainties: true)
earth_normalisation_prior_file: "inputs/earth_uncertainty_cov.jld2"
# JLD2 file containing 'covariance' matrix and 'true' vector for Earth density uncertainties

# Solar model and neutrino production data
solar_model_file: "inputs/AGSS09_high_z.jld2"     # Solar structure and neutrino production regions
flux_model_file: "inputs/fluxes.jld2"             # Solar neutrino energy spectra
earth_model_file: "inputs/EARTH_MODEL_PREM_DENSE.dat"  # PREM Earth density profile
earth_uncertainty_file: "inputs/earth_uncertainty_4.5e-5.jld2"  # Earth matter uncertainties
solar_exposure_file: "inputs/solarExposure.csv"   # Detector exposure vs zenith angle

##### MCMC optimization (optional) #####

# Proposal covariance matrix from previous run (improves sampling efficiency)
# Uncomment to use covariance matrix from a previous posterior
# Must be JLD2 file with 'posterior_cov' matrix object
# proposal_matrix: "outputs/posterior_covariance.jld2"

##### Detector response files #####

# Monte Carlo samples for detector response matrices
# CSV files with columns: Etrue, Ereco, mask (selection), weights (optional)
reconstruction_sample_CC: "inputs/sergio_reco_CC_withFullCuts.csv"
reconstruction_sample_ES_nue: "inputs/CC_reconstruction_fullEFF.csv"      # ES ν_e interactions
reconstruction_sample_ES_nuother: "inputs/CC_reconstruction_fullEFF.csv"  # ES ν_μ,τ interactions

##### Background Monte Carlo files #####

# Background event samples (must match number of components in normalisations above)
CC_background_files: ["inputs/neutron_bg_CC_sergio_withFullCuts.csv", 
                      "inputs/gamma_bg_CC_sergio_withFullCuts.csv"]
ES_background_files: ["inputs/Ereco_NGamma_1e6-1_evts_GeV_june2025_v2.csv"]

##### Real data file (only used when Asimov: false) #####

data_file: "data.txt"   # Real data file (format TBD)
