###############################
##### Output and run type #####

outFile: "outputs/both_leptonReco_3MeV_woBG_PDGlike_fast"    # Files are nominally saved in the outputs folder as jld2 or csv files with the appropriate suffixes
LLH: false    # Log Likelihood scan or MCMC fit
Asimov: true    # Data fit or Asimov fit?
fastFit: true    # Accelerate calculations by evaluating parameters at bin centers instead of averaging and evaluating oscprob at the average solar density

##########################
##### Asimov details #####

true_sin2_th12: 0.304
true_sin2_th13: 0.0224
true_dm2_21: 7.53e-5 # PDG: 7.53e-5,  SNO: 5.113e-5


###########################
##### MCMC parameters #####

nChains: 12
nSteps: 50000
nTuning: 20000
maxTuningAttempts: 30


##########################
##### LLH parameters #####

llh_bins: 150


########################################
##### MC and fit properties #####

CC_flux_normalisation: 619
CC_background_normalisation: 1.0

ES_flux_normalisation: 47000
ES_background_normalisation: 1.0

nBins: 20
energy_range: [0.1, 16]
emin_ES: 3
emin_CC: 3


#######################
##### Input files #####

solar_model_file: "inputs/AGSS09_high_z.jld2"
flux_model_file: "inputs/fluxes.jld2"

reconstruction_sample_CC: "inputs/Enu_Esmeared_CC.csv"
reconstruction_sample_ES_nue: "inputs/Enu_Esmeared_nue.csv"
reconstruction_sample_ES_nuother: "inputs/Enu_Esmeared_numunutau.csv"

CC_background_file: "inputs/Ereco_NGamma_1e6-1_evts.csv"
ES_nue_background_file: "inputs/Ereco_NGamma_1e6-1_evts.csv"
ES_nuother_background_file: "inputs/Ereco_NGamma_1e6-1_evts.csv"

data_file: "data.txt"
